import { NextResponse } from "next/server";
import { currentUser } from "../../../../lib/auth";
import { deleteDocumentFile } from "../../../../lib/document-storage";
import { prisma } from "../../../../lib/prisma";
import { tripAccess } from "../../../../lib/trip-access";

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const user = await currentUser(); if (!user) return NextResponse.json({ error: "Accesso richiesto" }, { status: 401 }); const { id } = await params; const access = await tripAccess(id, user); if (!access.allowed) return NextResponse.json({ error: access.missing ? "Viaggio non trovato" : "Accesso negato" }, { status: access.missing ? 404 : 403 }); const trip = await prisma.trip.findUnique({ where: { id }, include: { owner: { select: { id: true, name: true, email: true } }, activities: true, bookings: true, documents: true, expenses: true, participants: true } }); return NextResponse.json({ ...trip, accessRole: access.role }); }

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await currentUser(); if (!user) return NextResponse.json({ error: "Accesso richiesto" }, { status: 401 }); const { id } = await params; const access = await tripAccess(id, user); if (!access.allowed || access.role === "participant") return NextResponse.json({ error: "Non hai il permesso di modificare il viaggio" }, { status: 403 }); const body = await request.json(); if (body.archived !== undefined && access.role !== "owner") return NextResponse.json({ error: "Solo il proprietario può archiviare il viaggio" }, { status: 403 }); const trip = await prisma.trip.update({ where: { id }, data: { name: body.name, country: body.country, countryCode: body.countryCode, city: body.city, startDate: body.startDate ? new Date(`${body.startDate}T12:00:00`) : undefined, endDate: body.endDate ? new Date(`${body.endDate}T12:00:00`) : undefined, people: body.people === undefined ? undefined : Number(body.people), theme: body.theme, budget: body.budget, archivedAt: body.archived === undefined ? undefined : body.archived ? new Date() : null } }); return NextResponse.json(trip); }

export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const user = await currentUser(); if (!user) return NextResponse.json({ error: "Accesso richiesto" }, { status: 401 }); const { id } = await params; const access = await tripAccess(id, user); if (!access.allowed || access.role !== "owner") return NextResponse.json({ error: "Solo il proprietario può eliminare il viaggio" }, { status: 403 }); const documents = await prisma.document.findMany({ where: { tripId: id }, select: { storageKey: true } }); await Promise.all(documents.map((document) => deleteDocumentFile(document.storageKey))); await prisma.trip.delete({ where: { id } }); return NextResponse.json({ deleted: true }); }
