PRAGMA foreign_keys=ON;

CREATE TABLE "Trip" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "country" TEXT NOT NULL, "countryCode" TEXT NOT NULL, "city" TEXT NOT NULL, "startDate" DATETIME NOT NULL, "endDate" DATETIME NOT NULL, "people" INTEGER NOT NULL DEFAULT 1, "theme" TEXT NOT NULL DEFAULT 'blue', "budget" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "Activity" ("id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "day" INTEGER NOT NULL, "title" TEXT NOT NULL, "place" TEXT NOT NULL, "time" TEXT NOT NULL, "done" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "Activity_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Booking" ("id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "title" TEXT NOT NULL, "type" TEXT NOT NULL, "startDate" DATETIME NOT NULL, "endDate" DATETIME, "reference" TEXT, "status" TEXT NOT NULL DEFAULT 'pending', CONSTRAINT "Booking_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Document" ("id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "fileName" TEXT NOT NULL, "size" INTEGER NOT NULL, "offline" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "Document_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Expense" ("id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "description" TEXT NOT NULL, "amount" REAL NOT NULL, "category" TEXT NOT NULL, "paidBy" TEXT NOT NULL, "date" DATETIME NOT NULL, "sharedWith" TEXT, "kind" TEXT NOT NULL DEFAULT 'expense', "recipient" TEXT, CONSTRAINT "Expense_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Participant" ("id" TEXT NOT NULL PRIMARY KEY, "tripId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'participant', "status" TEXT NOT NULL DEFAULT 'pending', CONSTRAINT "Participant_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Participant_tripId_email_key" ON "Participant"("tripId", "email");
