"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Bell, CalendarClock, Save } from "lucide-react";
import { useRouter } from "next/navigation";

type Preferences = { invites: boolean; itineraryChanges: boolean; bookingUpdates: boolean; expenseUpdates: boolean; documentUpdates: boolean; tripReminders: boolean; activityReminders: boolean; reminderDaysBefore: number; activityHoursBefore: number };
const initial: Preferences = { invites: true, itineraryChanges: true, bookingUpdates: true, expenseUpdates: true, documentUpdates: true, tripReminders: true, activityReminders: true, reminderDaysBefore: 7, activityHoursBefore: 24 };
const options: Array<[keyof Preferences, string, string]> = [["invites", "Inviti e partecipanti", "Nuovi inviti e conferme del gruppo"], ["itineraryChanges", "Modifiche itinerario", "Attività aggiunte, spostate o modificate"], ["bookingUpdates", "Prenotazioni", "Aggiornamenti e prenotazioni da verificare"], ["expenseUpdates", "Spese", "Nuove spese e modifiche ai movimenti"], ["documentUpdates", "Documenti", "File condivisi e documenti mancanti"], ["tripReminders", "Promemoria partenza", "Avvisi prima dell’inizio del viaggio"], ["activityReminders", "Attività imminenti", "Promemoria prima delle attività in programma"]];

export default function NotificationSettingsPage() { const router = useRouter(); const [preferences, setPreferences] = useState(initial); const [saved, setSaved] = useState(false); useEffect(() => { fetch("/api/notification-preferences").then((response) => response.ok ? response.json() : null).then((result) => { if (result) setPreferences(result); }).catch(() => undefined); }, []); async function save() { const response = await fetch("/api/notification-preferences", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(preferences) }); if (response.ok) { setSaved(true); window.setTimeout(() => setSaved(false), 1800); } }
  return <main className="preference-shell"><header><button className="icon-button" onClick={() => router.push("/auth")}><ArrowLeft size={20} /></button><button className="detail-brand home-brand-button" onClick={() => router.push("/")}>mova</button></header><section className="preference-card"><div className="preference-heading"><span><Bell size={25} /></span><div><p className="section-kicker">PREFERENZE</p><h1>Notifiche e promemoria</h1><p>Scegli quali aggiornamenti vuoi ricevere.</p></div></div><div className="preference-list">{options.map(([key, title, description]) => <label key={key}><div><strong>{title}</strong><span>{description}</span></div><input type="checkbox" checked={Boolean(preferences[key])} onChange={(event) => setPreferences({ ...preferences, [key]: event.target.checked })} /></label>)}</div><div className="reminder-timing"><div><CalendarClock size={21} /><div><strong>Anticipo promemoria</strong><span>Personalizza quando ricevere gli avvisi.</span></div></div><label>Partenza<select value={preferences.reminderDaysBefore} onChange={(event) => setPreferences({ ...preferences, reminderDaysBefore: Number(event.target.value) })}><option value={1}>1 giorno prima</option><option value={3}>3 giorni prima</option><option value={7}>7 giorni prima</option><option value={14}>14 giorni prima</option><option value={30}>30 giorni prima</option></select></label><label>Attività<select value={preferences.activityHoursBefore} onChange={(event) => setPreferences({ ...preferences, activityHoursBefore: Number(event.target.value) })}><option value={1}>1 ora prima</option><option value={3}>3 ore prima</option><option value={12}>12 ore prima</option><option value={24}>1 giorno prima</option><option value={48}>2 giorni prima</option></select></label></div><button className="primary-button preference-save" onClick={save}><Save size={18} /> {saved ? "Preferenze salvate" : "Salva preferenze"}</button></section></main>;
}
